apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-signal-logger
  name: k8s-signal-logger
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-signal-logger
  type: NodePort
